version: '3.8'

services:
  db:
    image: "postgres:${POSTGRES_VERSION}"
    container_name: ${CONTAINER_NAME}
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    ports:
      - "${POSTGRESDB_LOCAL_PORT}:5432"
    volumes:
      - postgres_django:/var/lib/postgresql/data/
      - ./postgresql.conf /etc/postgresql.conf
      - ./logs:/logs
    networks:
       django:
         aliases:
           - Django
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U" ]
      timeout: 45s
      interval: 10s
      retries: 10

networks:
  django:
    driver: bridge

volumes:
  postgres_django:
    driver: local